### ISSUE TITLE
Adapter stops the whole time

### ISSUE THREAD

**Issue by radebold** [iobroker-community-adapters/ioBroker.xs1#1]
adapter try to start, but the interupted and stoped with error

`Terminated (ADAPTER_REQUESTED_TERMINATION): xs1 Initialization Error:TypeError: Cannot read properties of undefined (reading '_subscribeForeignStates') at subscribeStates (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:7387:21) at /opt/iobroker/node_modules/iobroker.xs1/myAdapter.js:709:111 at new Promise (<anonymous>) at /opt/iobroker/node_modules/iobroker.xs1/myAdapter.js:709:20 at /opt/iobroker/node_modules/iobroker.xs1/myAdapter.js:267:81`

**Comment by SamLowrie** [comment]
Habe jetzt den gleichen Fehler nach Update auf aktuellen Scripting-Host (5.0.8). Adapter started nicht mehr. Meine Javascript-Kentnisse sind leider nicht gut genug um zu verstehen, was an dieser Stelle passiert, bzw. falsch läuft (myAdapter.js, Zeile 709).

**Comment by SamLowrie** [comment]
Hab jetzt etwas google recherchiert. Habe einen anderen Adapter gefunden, der das gleiche Problem mit der gleichen Codezeile hatte (km200 Adapter, [Commit](https://github.com/iobroker-community-adapters/ioBroker.km200/commit/3a556b03eb12b3426b089d2e25e6d63f95ec3695).

Wenn man in myAdapter.js die Zeile 267 ersetzt durch die Zeile aus dem km200 Adapter startet der Adapter wieder und ich bekomme auch wieder Sensorwerte vom XS1 rein.

```
//.then(() => stateChange ? MyAdapter.c2p(adapter.subscribeStates)('*') : null)
.then(() => stateChange ? adapter.subscribeStates('*') : null)
```

Diff
```
267c267,268
<                 .then(() => stateChange ? MyAdapter.c2p(adapter.subscribeStates)('*') : null)
---
>                 //.then(() => stateChange ? MyAdapter.c2p(adapter.subscribeStates)('*') : null)
>               .then(() => stateChange ? adapter.subscribeStates('*') : null)
```

Da ich aber nicht wirklich verstehe was in der Zeile passiert kann ich nicht sagen ob daß das Problem wirklich löst oder dadurch andere Probleme entstehen, daher mach ich mal lieber keinen PR draus.

**Comment by descco** [comment]
Hallo SamLowrie,

Ich kann den Fix (Workaround) bestätigen.

Siehe auch 
https://forum.iobroker.net/topic/3516/mein-erster-adapter-f%C3%BCr-ezcontrol-xs1/100

**Comment by mcm1957** [comment]
fixed with 1.1.1-alpha.0
