### ISSUE TITLE
Update stable version in repo from 1.0.2 to 1.1.2

### ISSUE THREAD

**Issue by GermanBluefox** [iobroker-community-adapters/ioBroker.xs1#32]
# Think about update stable version to 1.1.2
**Version**: stable=**1.0.2** (2270 days old) => latest=**1.1.2** (15 days old)
**Installs**: stable=**43** (47.25%), latest=**12** (13.19%), total=**91**

Click to use [developer portal](https://www.iobroker.dev/adapter/xs1/releases)
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L2968)

Note: This is an automatically generated message and not personally authored by bluefox!

**Comment by mcm1957** [comment]
Is there any reason to delay updating stable any longer?
Please drop a commit if you know any reason to refrain from updating.

**If there is no response until 20.01.2024 we could decide to update anyway**

**Comment by mcm1957** [comment]
outdated

**Comment by GermanBluefox** [comment]
This issue seems to be outdated.

This issue suggests to update the stable version of this adapter to 1.1.2 but in the meantime an update to version 1.2.0 is suggested.

So this issue will be closed and replaced by an updated one.

@mcm1957 for evidence
